import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import QueryProviders from "@/provider/query.provider";

import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
    title: "Chat app",
    description: "Generated by create next app",
};

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geist.variable} antialiased`}>
                <QueryProviders>{children}</QueryProviders>
                <Toaster />
            </body>
        </html>
    );
}
