version: "2"
sql:
  - engine: "postgresql"
    queries: "infrastructure/db/sqlc/queries/"
    schema: "infrastructure/db/sqlc/schema/"
    gen:
      go:
        package: "infrastructure/db/sqlc/out"
        out: "infrastructure/db/sqlc/out"
        sql_package: "pgx/v5"